[package]
name = "elulib_mobile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
tauri = { version = "2.1", features = [] }

[build-dependencies]
tauri-build = { version = "2.1", features = [] }
